# Generated by Django 5.2.15 on 2026-06-08 14:22

from django.db import migrations


def set_default_year(apps, schema_editor):
    # IMMER: korrekte Modellversion über apps.get_model 
    Book = apps.get_model("catalog", "Book")
    Book.objects.filter(publication_year__isnull=True).update(publication_year = 2000)

class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_book_publication_year"),
    ]

    operations = [migrations.RunPython(set_default_year, migrations.RunPython.noop )]
