# Generated by Django 5.2.15 on 2026-06-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_checklistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="cv",
            field=models.FileField(blank=True, upload_to="cv/"),
        ),
    ]
